### ISSUE TITLE
User should be able to make their own Project hidden / visible

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#98]
Right now only a super user can make User projects visible / hidden.

Users should be able to make their own projects Hidden or Visible.

**Comment by mvexel** [comment]
As discussed: 

* We will make this possible
* Default will be for Project and Challenge to be Hidden.

**Comment by mgcuthbert** [comment]
Fixed per PR #132

**Comment by mvexel** [comment]
When logged in as a non-admin user, I still can't make my project visible.

**Comment by mgcuthbert** [comment]
Fixed in latest PR.
